### ISSUE TITLE
Spotify rich presence breaks upon loading plugin.

### ISSUE THREAD

**Issue by slowwspeed** [Socketlike/NoSpotifyPause#1]
Hello, I noticed recently that when I load this plugin lately, my rich presence for spotify does not show up. But when I unload the plugin it returns to normal. Just thought I should let you know.

**Comment by slowwspeed** [comment]
nvm it works now

**Comment by Socketlike** [comment]
[v1.0.5](https://github.com/Socketlike/NoSpotifyPause/releases/tag/v1.0.5) should fix this if you're still experiencing this issue
